
---
environment:
  matrix:
  - PYTHON: "C:\\Python36"

version: 1.0.{build}
image: Visual Studio 2019
install:
- SET PATH=%PYTHON%;%PYTHON%\\Scripts;%path%
- cmd: npm install
- "%PYTHON%\\python.exe -m pip install django django-cors-headers djangorestframework djangorestframework-simplejwt djangorestframework pillow PyJWT==1.7.1"

build_script:
- cmd: npm run build
test_script:
- cmd: npm run test
- "%PYTHON%\\python.exe djangoApi/manage.py test RecipeApp"
- "%PYTHON%\\python.exe djangoApi/manage.py test authentication"
