
---
environment:
  matrix:
  - PYTHON: "C:\\Python36\\python.exe"

version: 1.0.{build}
image: Visual Studio 2019
install:
- SET PATH=%PYTHON%;%path%
- cmd: npm install
- "%PYTHON% -m pip install django django-cors-headers djangorestframework djangorestframework-simplejwt djangorestframework pillow PyJWT==1.7.1"

build_script:
- cmd: npm run build
test_script:
- cmd: npm run test
- "%PYTHON% djangoApi/manage.py test"
