# Generated by Django 3.1.7 on 2021-03-10 20:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('UserId', models.AutoField(primary_key=True, serialize=False)),
                ('UserName', models.CharField(max_length=30, unique=True)),
                ('Password', models.CharField(max_length=50)),
                ('Email', models.EmailField(max_length=80)),
                ('JoinedDate', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='Recipes',
            fields=[
                ('RecipeId', models.AutoField(primary_key=True, serialize=False)),
                ('Name', models.CharField(max_length=100, unique=True)),
                ('Description', models.CharField(max_length=10000)),
                ('Ingredients', models.CharField(max_length=10000)),
                ('Steps', models.CharField(max_length=10000)),
                ('PhotoFileName', models.CharField(max_length=100)),
                ('CreationDate', models.DateField()),
                ('CreatorId', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='RecipeApp.users')),
            ],
        ),
    ]
