# Generated by Django 3.1.7 on 2021-03-11 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeApp', '0002_auto_20210310_1540'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='CreationDate',
            field=models.DateField(auto_now=True),
        ),
    ]
