# Generated by Django 3.1.7 on 2021-03-12 02:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeApp', '0004_auto_20210311_1036'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Description',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='recipe',
            name='PhotoFileName',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
