# Generated by Django 3.1.7 on 2021-03-12 02:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('RecipeApp', '0006_auto_20210311_1913'),
    ]

    operations = [
        migrations.RenameField(
            model_name='recipe',
            old_name='Creator_id',
            new_name='Creator',
        ),
    ]
