# Generated by Django 3.1.7 on 2021-03-12 02:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('RecipeApp', '0007_auto_20210311_1913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='Creator',
            field=models.ForeignKey(db_column='Creator', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
